# Route 1: City of Imus to Indang, Cavite (Vice-Versa)
starting_place_1 = [
    'Indang',
    'Cuso',
    'Kaytapos',
    'Petron Alulod',
    'Alulod',
    'Metrogate',
    'M. Lupa/Brgy. Hall',
    'Checkpoint',
    'Regina',
    'Sampaguita',
    'Kodi',
    'Trece Martires City',
    'Concho',
    'Perez',
    'Metro South',
    'Metropolis',
    'Tinongan',
    'Manggahan',
    'Stateland',
    'Monterey',
    'FCIE-Langkaan',
    'Slaughter',
    'Pala-Pala',
    'San Agustin',
    'Dasmariñas',
    'Bauman',
    'Arcontica',
    'Salitran',
    'San Miguel',
    'Coastal Anabu',
    'Yazaki',
    'Doyets',
    'CBI',
    'Patindig Araw',
    'Robinson',
    'Pac Mac',
    'Imus Toll Dr.',
    'LTO',
    'SM Bacoor'
]

# Route 2: Dasmariñas Bagong Bayan to Imus (TP) (Vice-Versa)
starting_place_2 = [
    'DBBC Terminal',
    'Fatima I',
    'Windward Hills',
    'INC/Gov. Mangubat Ave.',
    'La Salle Medical Center',
    'Vel Maris School',
    'Kalipayan Resort',
    'Salitran',
    'Diamond Village',
    'Ford Cavite',
    'Mandarin Subdivision II',
    'EMI/Yazaki',
    'Anabu Hills',
    'Makro',
    'Robinson Imus',
    'Imus Palico',
    'Imus (TP)'
]

#  Route 3: Silang to Zapote (Vice-Versa)
starting_place_3 = [
    'Silang Proper',
    'Sabutan',
    'Petron Gas Station',
    'KR Lumber',
    'IIRR',
    'JDZ Security Agency',
    '---',
    'Euro Med Lab',
    'Metro Gate Subdivision',
    'Pala-pala',
    'Vine Yard',
    'San Agustin 2',
    'San Agustin 3',
    'Dasmariñas Proper',
    'Vel Maris School',
    'Kalipayan Resort',
    'Salitran',
    'Diamond Village',
    'Ford Cavite',
    'Mandarin Subdivision II',
    'EMI/Yazaki',
    'Anabu Hills',
    'Makro',
    'Robinson Imus',
    'Imus Palico',
    'LTO',
    'Justin Ville',
    'SM Bacoor',
    'Panapanaan',
    'Niog',
    'Zapote Bacoor'
]
